name: Snyk Security Scan

on:
  push:
    branches:
      - 'feature1'
  pull_request:
    branches:
      - '**'

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
